docs: link styling (refs SFKUI-6446)
Forsakringskassan/docs-generator pull request #16
Opened 2024-05-03 13:05 UTC by krehnst

Styling för länkar -- vad jag försöker göra här är att stajla länkar i innehållet, men inte de som är rubriker, eller i menyer etc. 
se bild nedan
![image](https://github.com/Forsakringskassan/docs-generator/assets/168091715/c5ff8629-662e-4a8d-9442-82ab28df60e1)

+ ändringar i package-lock.jason så den hänvisar till npmjs.org istället för npmjs.com

2024-05-06 06:41 UTC, ext commented on src/style/core.scss
> +    color: var(--f-text-color-default);
Det är nog bra om vi lägger in en ny variabel i [`css-variables.mjs`](https://github.com/Forsakringskassan/docs-generator/blob/main/src/style/css-variables.mjs) istället så vi inte bygger in / tvingar FKUI här.

Nuvarande variabler kan visas under [Theme](https://forsakringskassan.github.io/docs-generator/theme/) i menyn, det finns några nya som inte är släppta än.

2024-05-06 09:36 UTC, ext requested changes

2024-05-06 14:39 UTC, krehnst commented on package.json
> +    "@forsakringskassan/docs-generator": "1.27.0",
nepp, vet inte vad den gjorde där

2024-05-06 14:47 UTC, ext commented
- [ ] Squash commits

2024-05-08 10:54 UTC, ext approved these changes

2024-05-08 12:42 UTC, merged