feat: generate component links (fixes SFKUI-6698)
Forsakringskassan/docs-generator pull request #41
Opened 2024-08-16 12:28 UTC by dvitamin

2024-08-16 12:32 UTC, dvitamin commented on src/processors/source-url-processor.ts
> +            return undefined;
Kluven till hur vi gör med felhantering här. Om man får flera träffar eller ingen träff så bör det smälla - såvida man ibland inte vill ha en komponent på sidan _utan_ länk till någon källkodsfil. Är det ett usecase som kan inträffa?

2024-08-21 15:10 UTC, dvitamin commented on src/processors/source-url-processor.ts
> +            return undefined;
Landade i att det alltid bör smälla.

2024-08-21 15:30 UTC, dvitamin commented on src/render/inline-tags/link.spec.ts
> +        "<a href="./f-components.html">with-components</a>
Undersök

2024-08-22 05:46 UTC, MCFK approved these changes

2024-08-22 07:02 UTC, ext requested changes

2024-08-22 07:02 UTC, ext commented on src/processors/source-url-processor.ts
> +        component: string | Component,
Kan detta hända då data normaliserats i `frontMatterFileReader`?

2024-08-22 07:11 UTC, dvitamin commented on src/processors/source-url-processor.ts
> +        component: string | Component,
Tänkte att man kanske vill anropa template-funktionen rakt av i något sammanhang med enkel namn-sträng. Men det kan vi ju lägga till stöd för vid behov såfall. Tar bort.

2024-08-22 08:53 UTC, dvitamin commented on src/processors/source-url-processor.ts
> +        async handler(context) {
Fixat

2024-08-22 08:54 UTC, dvitamin commented on src/render/inline-tags/link.spec.ts
> +        "<a href="./f-components.html">with-components</a>
Fixat

2024-08-22 08:54 UTC, dvitamin commented on src/processors/source-url-processor.ts
> +        return path.join(baseUrl, relativeUrl);
Körde på interpolate.

2024-08-22 10:48 UTC, ext approved these changes

2024-08-22 11:16 UTC, merged