feat: add option enable to `selectableVersionProcessor`
Forsakringskassan/docs-generator pull request #42
Opened 2024-08-21 13:11 UTC by MCFK

2024-08-21 14:24 UTC, dvitamin approved these changes

2024-08-22 06:42 UTC, ext requested changes

2024-08-22 06:42 UTC, ext commented on src/processors/selectable-version-processor.ts
> +import { VersionProcessorOptions } from "./version-processor";
Är det inte bättre skapa upp ett eget interface `SelectableVersionProcessor` eftersom `VersionProcessorOptions` innehåller orelaterade inställningar (exempelvis `scm`).

2024-08-22 07:00 UTC, MCFK commented on src/processors/selectable-version-processor.ts
> +import { VersionProcessorOptions } from "./version-processor";
Jo, det hade ju blivit snyggare. Ser nu att det redan finns ett interface som är mer generellt.
https://github.com/Forsakringskassan/docs-generator/blob/main/src/processor.ts#L7
Kanske är bättre att byta till det?

2024-08-22 07:12 UTC, ext commented on src/processors/selectable-version-processor.ts
> +import { VersionProcessorOptions } from "./version-processor";
Det hade också fungerat.

2024-08-22 07:27 UTC, MCFK commented on src/processors/selectable-version-processor.ts
> +import { VersionProcessorOptions } from "./version-processor";
Fixat

2024-08-22 10:49 UTC, ext approved these changes

2024-08-22 10:56 UTC, merged